# Generated by IBM TransformationAdvisor
# Tue Nov 16 19:20:43 UTC 2021

FROM ibmcom/websphere-traditional:latest-ubi

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/config/lib
COPY --chown=was:root modresorts-1.0.war /work/config/modresorts-1.0.war
COPY --chown=was:root ./src/config /work/config
COPY --chown=was:root ./lib /work/config/lib
RUN /work/configure.sh
